'regression-test/../expected.yaml' updated after latest changes

diff --git a/regression-test/data/overwrite_registry/expected.yaml b/regression-test/data/overwrite_registry/expected.yaml
--- a/regression-test/data/overwrite_registry/expected.yaml
+++ b/regression-test/data/overwrite_registry/expected.yaml
@@ -46,9 +46,7 @@ metadata:
     tif.telekom.de/group: tif
 type: Opaque
 data:
-  license: ""
   gatewayAdminBase64: "WVdSdGFXNDZZMmhoYm1kbGJXVT0="
-  kongAdminPassword: "Y2hhbmdlbWU="
   postgresPassword: "Y2hhbmdlbWU="
 ---
 # Source: stargate/templates/configmap-configuration.yaml
@@ -249,7 +247,8 @@ data:
     log_format log_proxy_json '{ "@timestamp": "$time_iso8601", '
                                  '"@service": "proxy", '
                                  '"@fields": { '
-                                   '"source": "$http_x_real_ip", '
+                                   '"source": "$http_x_original_forwarded_for", '
+                                   '"source_internal": "$http_x_real_ip", '
                                    '"status": "$status", '
                                    '"request_method": "$request_method", '
                                    '"request_path": "$uri", '
@@ -258,13 +257,14 @@ data:
                                    '"X-B3-TraceId": "$http_x_b3_traceid", '
                                    '"upstream_status": "$upstream_status", '
                                    '"tardis_consumer": "$tardis_consumer", '
-                                   '"sec_event_code": "$sec_event_code", '
-                                   '"sec_event_details": "$sec_event_details", } }';
+                                   '"eventclassid": "$sec_event_code", '
+                                   '"event_details": "$sec_event_details" } }';
     
     log_format log_proxy_debug_json '{ "@timestamp": "$time_iso8601", '
                                  '"@service": "proxy", '
                                  '"@fields": { '
-                                   '"source": "$http_x_real_ip", '
+                                   '"source": "$http_x_original_forwarded_for", '
+                                   '"source_internal": "$http_x_real_ip", '
                                    '"status": "$status", '
                                    '"request_method": "$request_method", '
                                    '"request_path": "$uri", '
@@ -280,8 +280,8 @@ data:
                                    '"upstream_response_time": "$upstream_response_time", '
                                    '"upstream_status": "$upstream_status", '
                                    '"tardis_consumer": "$tardis_consumer", '
-                                   '"sec_event_code": "$sec_event_code", '
-                                   '"sec_event_details": "$sec_event_details", '
+                                   '"eventclassid": "$sec_event_code", '
+                                   '"event_details": "$sec_event_details", '
                                    '"http_user_agent": "$http_user_agent" } }';
     
     # TARDIS log formats for admin port
@@ -289,19 +289,21 @@ data:
     log_format log_admin_json '{ "@timestamp": "$time_iso8601", '
                                  '"@service": "admin", '
                                  '"@fields": { '
-                                   '"source": "$http_x_real_ip", '
+                                   '"source": "$http_x_original_forwarded_for", '
+                                   '"source_internal": "$http_x_real_ip", '
                                    '"remote_user": "$remote_user", '
                                    '"status": "$status", '
                                    '"request_method": "$request_method", '
                                    '"request_path": "$uri", '
                                    '"hostname_ingress": "$host", '
-                                   '"sec_event_code": "$sec_event_code", '
-                                   '"sec_event_details": "$sec_event_details", } }';
+                                   '"eventclassid": "$sec_event_code", '
+                                   '"event_details": "$sec_event_details" } }';
     
     log_format log_admin_debug_json '{ "@timestamp": "$time_iso8601", '
                                  '"@service": "admin", '
                                  '"@fields": { '
-                                   '"source": "$http_x_real_ip", '
+                                   '"source": "$http_x_original_forwarded_for", '
+                                   '"source_internal": "$http_x_real_ip", '
                                    '"remote_user": "$remote_user", '
                                    '"status": "$status", '
                                    '"request_method": "$request_method", '
@@ -317,8 +319,8 @@ data:
                                    '"connection_requests": "$connection_requests", '
                                    '"hostname_ingress": "$host", '
                                    '"hostname_pod": "$hostname", '
-                                   '"sec_event_code": "$sec_event_code", '
-                                   '"sec_event_details": "$sec_event_details", '
+                                   '"eventclassid": "$sec_event_code", '
+                                   '"event_details": "$sec_event_details", '
                                    '"http_user_agent": "$http_user_agent" } }';
     
     server {
@@ -330,7 +332,7 @@ data:
         error_page 400 404 408 411 412 413 414 417 494 /kong_error_handler;
         error_page 500 502 503 504                     /kong_error_handler;
     
-        access_log ${{PROXY_ACCESS_LOG}} ;
+        access_log ${{PROXY_ACCESS_LOG}} log_proxy_json;
         error_log  ${{PROXY_ERROR_LOG}} ${{LOG_LEVEL}};
     
     > if proxy_ssl_enabled then
@@ -595,7 +597,7 @@ data:
         listen $(entry.listener);
     > end
     
-        access_log ${{ADMIN_ACCESS_LOG}} ;
+        access_log ${{ADMIN_ACCESS_LOG}} log_admin_json;
         error_log  ${{ADMIN_ERROR_LOG}} ${{LOG_LEVEL}};
     
     > if admin_ssl_enabled then
@@ -886,7 +888,7 @@ metadata:
   name: stargate
   annotations:
     ops.eni.telekom.de/pipeline-meta-ref: stargate-pipeline-metadata
-    checksum/secret-kong: 3ba5c182641e1ae13c7d4504069c1078389215bac6f68b201b5dd325875c6b77
+    checksum/secret-kong: bd185f9081a2e302ad44b28419ceeef27d06e93ad30a35a258dc199479abf841
     checksum/secret-issuer-service: da62a251a3ed5607f7ebc6af113f05cf1f00c6e174270fb7e7ef6572ac4d1b32
   labels: 
     app: stargate
@@ -904,7 +906,7 @@ spec:
     metadata:
       annotations:
         ops.eni.telekom.de/pipeline-meta-ref: stargate-pipeline-metadata
-        checksum/secret-kong: 3ba5c182641e1ae13c7d4504069c1078389215bac6f68b201b5dd325875c6b77
+        checksum/secret-kong: bd185f9081a2e302ad44b28419ceeef27d06e93ad30a35a258dc199479abf841
         checksum/secret-issuer-service: da62a251a3ed5607f7ebc6af113f05cf1f00c6e174270fb7e7ef6572ac4d1b32
         prometheus.io/path: '/metrics'
         prometheus.io/scrape: 'true'
@@ -935,35 +937,6 @@ spec:
                   values:
                   - stargate-kong
               topologyKey: "kubernetes.io/hostname"
-      initContainers:
-      - name: kong-install-plugins
-        image: some-other-registry.telekom.de/tardis/kong-plugins:2.1.3
-        imagePullPolicy: IfNotPresent
-        securityContext: 
-          {}
-        resources: 
-          limits:
-            cpu: 0.5
-            memory: 500Mi
-          requests:
-            cpu: 50m
-            memory: 200Mi
-        command:
-        - /bin/sh
-        - -c
-        - |-
-          mkdir -p /tmp/plugins
-          cp -r /usr/local/kong/plugins/. /tmp/plugins
-          luarocks-admin make-manifest /tmp/plugins
-          luarocks --from=/tmp/plugins install --local kong-plugin-jwt-keycloak
-          luarocks --from=/tmp/plugins install --local kong-plugin-eni-zipkin
-          luarocks --from=/tmp/plugins install --local kong-plugin-eni-prometheus
-          luarocks --from=/tmp/plugins install --local luaossl OPENSSL_DIR=/usr/local/kong CRYPTO_DIR=/usr/local/kong
-        volumeMounts:        
-        - name: local-luarocks
-          mountPath: /home/kong/.luarocks
-        - name: kongplugins-tmp
-          mountPath: /tmp
       containers:
       - name: jumper
         image: some-other-registry.telekom.de/tardis/jumper-sse:2.3.5
@@ -1056,7 +1029,7 @@ spec:
               name: stargate-issuer-service
               key: publicKey
       - name: kong
-        image: some-other-registry.telekom.de/tardis/kong:2.8.1-alpine
+        image: some-other-registry.telekom.de/tardis-internal/io/eni-kong:2.8.3.3
         imagePullPolicy: IfNotPresent
         securityContext: 
           {}
@@ -1068,7 +1041,7 @@ spec:
         - name: KONG_NGINX_HTTP_LUA_SHARED_DICT
           value: 'prometheus_metrics 15m'        
         - name: KONG_PLUGINS
-          value: bundled,eni-zipkin,jwt-keycloak,eni-prometheus
+          value: bundled,jwt-keycloak
         - name: KONG_LUA_PACKAGE_PATH
           value: "/opt/?.lua;;"        
         - name: KONG_MEM_CACHE_SIZE
@@ -1097,10 +1070,12 @@ spec:
         - name: KONG_PROXY_ERROR_LOG
           value: "/dev/stderr"
         - name: KONG_SSL_CIPHER_SUITE
-          value: custom
+          value: "custom"
         - name: KONG_SSL_CIPHERS
-          value: ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES256-SHA256:DHE-DSS-AES128-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
-        - name: KONG_NGINX_HTTP_SSL_PROTOCOLS
+          value: "DHE-DSS-AES128-SHA256:DHE-DSS-AES256-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES128-CCM:DHE-RSA-AES256-CCM:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-CCM:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256"
+        - name: KONG_SSL_PROTOCOLS
+          value: "TLSv1.2 TLSv1.3"
+        - name: KONG_LUA_SSL_PROTOCOLS
           value: "TLSv1.2 TLSv1.3"
         - name: KONG_PROXY_LISTEN
           value: '0.0.0.0:8000'
@@ -1171,8 +1146,6 @@ spec:
         - name: nginx-servers
           mountPath: /opt/kong/nginx
       volumes:      
-      - name: kongplugins-tmp
-        emptyDir: {}      
       - name: local-luarocks
         emptyDir: {}
       - name: kong-prefix-dir
@@ -1435,7 +1408,7 @@ spec:
   template:
     spec:      
       containers:
-      - name: stargate-kong-admin-route
+      - name: kong-admin-route
         image: some-other-registry.telekom.de/tardis/tif-base-image:1.0.0
         imagePullPolicy: IfNotPresent
         securityContext: 
@@ -1479,7 +1452,7 @@ spec:
   template:
     spec:      
       containers:
-      - name: stargate-prometheus-setup
+      - name: prometheus-setup
         image: some-other-registry.telekom.de/tardis/tif-base-image:1.0.0
         securityContext: 
           {}
@@ -1489,37 +1462,110 @@ spec:
             secretKeyRef:
               name: stargate
               key: gatewayAdminBase64
-        - name: KONG_ADMIN_PASSWORD
-          valueFrom:
-            secretKeyRef:
-              name: stargate
-              key: kongAdminPassword
         command:        
           - /bin/bash
           - -c
           - |-
-            echo "Enabling Kong plugin via PUT http://stargate-admin.default:8001/plugins"
+            echo "Enabling Kong ENI flavoured Prometheus plugin via PUT http://stargate-admin.default:8001/plugins"
 
-            HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" -X GET http://stargate-admin.default:8001`
-            if [ "$HTTP_RETURN_CODE" == "200" ]; then
-              curl \
-              -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
-              -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
-              -X PUT http://stargate-admin.default:8001/plugins/3d232d3c-dc2b-4705-aa8d-4e07c4e0ff4c \
-              --header 'Content-Type: application/json' \
-              --data \
-              '{
-                "name" : "eni-prometheus",
-                "tags" : ["tardis","eni-prometheus"],
-                "config" : {
-                  "customer_facing" : "false",
-                  "eni_stat" : true
-                }
-              }'
-            else
+            ADMIN_API_HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" -X GET http://stargate-admin.default:8001`
+            if [ "$ADMIN_API_HTTP_RETURN_CODE" != "200" ]; then
                 echo "Kong Admin-API unreachable"
                 exit 1
             fi
+
+            CONFIG_CALL_HTTP_RETURN_CODE=`curl \
+            -o /dev/null \
+            -w "%{http_code}" \
+            -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
+            -X PUT http://stargate-admin.default:8001/plugins/3d232d3c-dc2b-4705-aa8d-4e07c4e0ff4c \
+            --header 'Content-Type: application/json' \
+            --data \
+            '{
+              "name" : "prometheus",
+              "tags" : ["tardis","prometheus","eni-prometheus"],
+              "config" : {
+                "customer_facing" : "false",
+                "status_code_metrics" : true,
+                "latency_metrics" : true,
+                "upstream_health_metrics" : true,
+                "bandwidth_metrics" : true,
+                "per_consumer" : true,
+                "eni_stat" : true
+              }
+            }'`
+
+            if [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "200" ] && [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "201" ]; then
+              echo "Configuring plugin failed"
+              exit 1
+            fi
+      restartPolicy: OnFailure
+---
+# Source: stargate/templates/job-request-size-limiting-setup.yml
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: stargate-request-rate-limiting-setup
+  labels: 
+    app: stargate
+    app.kubernetes.io/name: kong
+    app.kubernetes.io/instance: stargate-kong
+    app.kubernetes.io/component: api-gateway
+    app.kubernetes.io/part-of: tif-runtime
+    tif.telekom.de/group: tif
+  annotations:
+    "helm.sh/hook": post-install,post-upgrade
+    "helm.sh/hook-delete-policy": before-hook-creation
+spec:
+  backoffLimit: 15
+  activeDeadlineSeconds: 3600
+  template:
+    spec:      
+      containers:
+      - name: request-size-limiting-setup
+        image: some-other-registry.telekom.de/tardis/tif-base-image:1.0.0
+        securityContext: 
+          {}
+        env:
+        - name: X_TARDIS_GATEWAY_ADMIN_BASE64
+          valueFrom:
+            secretKeyRef:
+              name: stargate
+              key: gatewayAdminBase64
+        command:        
+          - /bin/bash
+          - -c
+          - |- 
+            echo "Enabling Kong request-rate-limiting plugin via PUT http://stargate-admin.default:8001/plugins"
+
+            ADMIN_API_HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" -X GET http://stargate-admin.default:8001`
+            if [ "$ADMIN_API_HTTP_RETURN_CODE" != "200" ]; then
+                echo "Kong Admin-API unreachable"
+                exit 1
+            fi
+
+            CONFIG_CALL_HTTP_RETURN_CODE=`curl \
+            -o /dev/null \
+            -w "%{http_code}" \
+            -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
+            -X PUT http://stargate-admin.default:8001/plugins/1e199eee-f592-4afa-8371-6b61dcbd1904 \
+            --header 'Content-Type: application/json' \
+            --data \
+            '{
+              "name": "request-size-limiting",
+              "tags" : ["tardis","request-size-limiting"],
+              "config" : {
+                "allowed_payload_size": 4,
+                "size_unit": "megabytes",
+                "require_content_length": false
+              }
+            }'`
+
+            if [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "200" ] && [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "201" ]; then
+              echo "Configuring plugin failed"
+              exit 1
+            fi
+
       restartPolicy: OnFailure
 ---
 # Source: stargate/templates/job-zipkin-setup.yml
@@ -1543,7 +1589,7 @@ spec:
   template:
     spec:      
       containers:
-      - name: tif-base-image
+      - name: zipkin-setup
         image: some-other-registry.telekom.de/tardis/tif-base-image:1.0.0
         securityContext: 
           {}
@@ -1553,38 +1599,40 @@ spec:
             secretKeyRef:
               name: stargate
               key: gatewayAdminBase64
-        - name: KONG_ADMIN_PASSWORD
-          valueFrom:
-            secretKeyRef:
-              name: stargate
-              key: kongAdminPassword
         command:        
           - /bin/bash
           - -c
           - |- 
-            echo "Enabling Kong eni-zipkin plugin via PUT http://stargate-admin.default:8001/plugins"
+            echo "Enabling Kong ENI flavoured Zipkin plugin via PUT http://stargate-admin.default:8001/plugins"
 
-            HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" -X GET http://stargate-admin.default:8001`
-            if [ "$HTTP_RETURN_CODE" == "200" ]; then
-              curl \
-              -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
-              -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
-              -X PUT http://stargate-admin.default:8001/plugins/e8ff1211-816f-4d93-9011-a4b194586073 \
-              --header 'Content-Type: application/json' \
-              --data \
-              '{
-                "name" : "eni-zipkin",
-                "tags" : ["tardis","eni-zipkin"],
-                "config" : {
-                  "http_endpoint" : "http://jaeger-collector.default:9411/api/v2/spans",
-                  "sample_ratio" : 0.001,
-                  "include_credential" : true,
-                  "default_service_name" : "stargate",
-                  "local_component_name" : "stargate"
-                }
-              }'
-            else
+            ADMIN_API_HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" -X GET http://stargate-admin.default:8001`
+            if [ "$ADMIN_API_HTTP_RETURN_CODE" != "200" ]; then
                 echo "Kong Admin-API unreachable"
                 exit 1
             fi
+
+            CONFIG_CALL_HTTP_RETURN_CODE=`curl \
+            -o /dev/null \
+            -w "%{http_code}" \
+            -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
+            -X PUT http://stargate-admin.default:8001/plugins/e8ff1211-816f-4d93-9011-a4b194586073 \
+            --header 'Content-Type: application/json' \
+            --data \
+            '{
+              "name" : "zipkin",
+              "tags" : ["tardis","zipkin","eni-zipkin"],
+              "config" : {
+                "http_endpoint" : "http://jaeger-collector.default:9411/api/v2/spans",
+                "sample_ratio" : 0.001,
+                "include_credential" : true,
+                "default_service_name" : "stargate",
+                "local_component_name" : "stargate"
+              }
+            }'`
+
+            if [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "200" ] && [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "201" ]; then
+              echo "Configuring plugin failed"
+              exit 1
+            fi
+
       restartPolicy: OnFailure
