Plugin jobs failover

diff --git a/templates/job-prometheus-setup.yml b/templates/job-prometheus-setup.yml
--- a/templates/job-prometheus-setup.yml
+++ b/templates/job-prometheus-setup.yml
@@ -36,27 +36,33 @@ spec:
           - |-
             echo "Enabling Kong ENI flavoured Prometheus plugin via PUT {{ include "kong.adminApi.serviceUrl" . }}/plugins"
 
-            HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" {{ if eq .Values.rbac.enabled true -}}-H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD"{{- end }} -X GET {{ include "kong.adminApi.serviceUrl" . }}`
-            if [ "$HTTP_RETURN_CODE" == "200" ]; then
-              curl \
-              -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
-            {{- if eq .Values.rbac.enabled true }}
-              -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
-            {{- end }}
-              -X PUT {{ include "kong.adminApi.serviceUrl" . }}/plugins/{{ .Values.prometheus.setupJob.pluginId }} \
-              --header 'Content-Type: application/json' \
-              --data \
-              '{
-                "name" : "prometheus",
-                "tags" : ["tardis","prometheus","eni-prometheus"],
-                "config" : {
-                  "customer_facing" : "{{ .Values.prometheus.setupJob.customer_facing | default false }}",
-                  "eni_stat" : true
-                }
-              }'
-            else
+            ADMIN_API_HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" {{ if eq .Values.rbac.enabled true -}}-H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD"{{- end }} -X GET {{ include "kong.adminApi.serviceUrl" . }}`
+            if [ "$ADMIN_API_HTTP_RETURN_CODE" == "200" ]; then
                 echo "Kong Admin-API unreachable"
                 exit 1
+            fi
+
+            CONFIG_CALL_HTTP_RETURN_CODE=`curl \
+            -w "%{http_code}" \
+            -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
+            {{- if eq .Values.rbac.enabled true }}
+            -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
+            {{- end }}
+            -X PUT {{ include "kong.adminApi.serviceUrl" . }}/plugins/{{ .Values.prometheus.setupJob.pluginId }} \
+            --header 'Content-Type: application/json' \
+            --data \
+            '{
+              "name" : "prometheus",
+              "tags" : ["tardis","prometheus","eni-prometheus"],
+              "config" : {
+                "customer_facing" : "{{ .Values.prometheus.setupJob.customer_facing | default false }}",
+                "eni_stat" : true
+              }
+            }'`
+
+            if [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "200" ] && [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "201"]; then
+              echo "Configuring plugin failed"
+              exit 1
             fi
       restartPolicy: OnFailure
 {{- end -}}
diff --git a/templates/job-zipkin-setup.yml b/templates/job-zipkin-setup.yml
--- a/templates/job-zipkin-setup.yml
+++ b/templates/job-zipkin-setup.yml
@@ -36,30 +36,37 @@ spec:
           - |- 
             echo "Enabling Kong ENI flavoured Zipkin plugin via PUT {{ include "kong.adminApi.serviceUrl" . }}/plugins"
 
-            HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" {{ if eq .Values.rbac.enabled true -}}-H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD"{{- end }} -X GET {{ include "kong.adminApi.serviceUrl" . }}`
-            if [ "$HTTP_RETURN_CODE" == "200" ]; then
-              curl \
-              -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
-              {{- if eq .Values.rbac.enabled true }}
-              -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
-              {{- end }}
-              -X PUT {{ include "kong.adminApi.serviceUrl" . }}/plugins/{{ .Values.zipkin.setupJob.pluginId }} \
-              --header 'Content-Type: application/json' \
-              --data \
-              '{
-                "name" : "zipkin",
-                "tags" : ["tardis","zipkin","eni-zipkin"],
-                "config" : {
-                  "http_endpoint" : "{{ .Values.zipkin.collectorUrl }}",
-                  "sample_ratio" : {{ .Values.zipkin.sampleRatio | default 0.001 }},
-                  "include_credential" : {{ .Values.zipkin.includeCredential | default true }},
-                  "default_service_name" : "{{ .Values.zipkin.defaultServiceName | default .Release.Name }}",
-                  "local_component_name" : "{{ .Values.zipkin.defaultServiceName | default .Release.Name }}"
-                }
-              }'
-            else
+            ADMIN_API_HTTP_RETURN_CODE=`curl -Is -o /dev/null -w "%{http_code}" -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" {{ if eq .Values.rbac.enabled true -}}-H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD"{{- end }} -X GET {{ include "kong.adminApi.serviceUrl" . }}`
+            if [ "$ADMIN_API_HTTP_RETURN_CODE" == "200" ]; then
                 echo "Kong Admin-API unreachable"
                 exit 1
             fi
+
+            CONFIG_CALL_HTTP_RETURN_CODE=`curl \
+            -w "%{http_code}" \
+            -H "Authorization:Basic $X_TARDIS_GATEWAY_ADMIN_BASE64" \
+            {{- if eq .Values.rbac.enabled true }}
+            -H "Kong-Admin-Token:$KONG_ADMIN_PASSWORD" \
+            {{- end }}
+            -X PUT {{ include "kong.adminApi.serviceUrl" . }}/plugins/{{ .Values.zipkin.setupJob.pluginId }} \
+            --header 'Content-Type: application/json' \
+            --data \
+            '{
+              "name" : "zipkin",
+              "tags" : ["tardis","zipkin","eni-zipkin"],
+              "config" : {
+                "http_endpoint" : "{{ .Values.zipkin.collectorUrl }}",
+                "sample_ratio" : {{ .Values.zipkin.sampleRatio | default 0.001 }},
+                "include_credential" : {{ .Values.zipkin.includeCredential | default true }},
+                "default_service_name" : "{{ .Values.zipkin.defaultServiceName | default .Release.Name }}",
+                "local_component_name" : "{{ .Values.zipkin.defaultServiceName | default .Release.Name }}"
+              }
+            }'`
+
+            if [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "200" ] && [ "$CONFIG_CALL_HTTP_RETURN_CODE" != "201"]; then
+              echo "Configuring plugin failed"
+              exit 1
+            fi
+
       restartPolicy: OnFailure
 {{- end }}
